### PR TITLE
Add Google Calendar integration

### PR DESCRIPTION
**Pull request by ebobrow**
This adds a calendar page, where users can view events from their Google Calendar and add them to their today view. In order to access a user's Google Calendar, there's an extra consent screen that they have to agree to when they log in, but unfortunately I don't believe there's any way around that.

I also added a new table to the database. I created a file in web-app/config.sql with the code. Let me know if there's anything you'd like me to change!

### CODE REVIEW

**Comment by zane-programs** [comment]
Sorry, I just saw this! I'll take a look at it in full when I have a moment. Thanks so much!

**Comment by ebobrow** [comment]
Awesome! No rush.

**Comment by zane-programs** [comment]
By the way, I tried your Schoop fork on my computer, and I noticed that deleting my account did not work when I still had calendar events in the database. Could you edit the `deleteAccount` function in `web-app/app/core/db.js` such that calendar events are deleted before the user itself is deleted? Thanks so much.

**Comment by ebobrow** [comment]
Huh, that's strange. It seems to work on my computer because of the `ON DELETE CASCADE` in the foreign key definition. I can add an extra query to the `deleteAccount` function instead, though, if it isn't working.

**Comment by zane-programs** [comment]
> Huh, that's strange. It seems to work on my computer because of the `ON DELETE CASCADE` in the foreign key definition. I can add an extra query to the `deleteAccount` function instead, though, if it isn't working.

Ha, my bad. I was using an old version of your `config.sql`. The `ON DELETE CASCADE` should work just fine. Sorry about that.

**Comment by zane-programs** [comment]
Okay, I've looked over your code and tried your fork of Schoop locally. I'll check to make sure that calendar events work as expected tomorrow morning, and if they do, then I will merge this pull request and our work here will be done! Huzzah!

Thanks so much for your contribution to this project. I know the circumstances may not be ideal, but I think we're building something important here. Hopefully it continues to be useful and helpful; I'm confident that this addition will help us in making sure that it does.

**Pull request merged**
